# Generated by Django 5.2.5 on 2025-08-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('Car Rental', 'Car Rental'), ('Driver Service', 'Driver Service'), ('Logistics', 'Logistics'), ('Flight Ticket', 'Flight Ticket'), ('Bus Ticket', 'Bus Ticket'), ('Train Ticket', 'Train Ticket')], help_text='The type of service requested by the user.', max_length=20)),
                ('details', models.JSONField(help_text='A JSON object containing the specific details from the submitted form.')),
                ('booking_date', models.DateTimeField(auto_now_add=True, help_text='The date and time when the booking was submitted.')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('shift_1_hours', models.CharField(max_length=50)),
                ('shift_2_hours', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('image_url', models.URLField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(help_text='The name of the customer giving the testimonial.', max_length=100)),
                ('quote', models.TextField(help_text='The content of the testimonial.')),
                ('rating', models.IntegerField(default=5, help_text='Rating from 1 to 5 stars.')),
                ('image_url', models.URLField(blank=True, help_text="URL to the author's profile picture.", max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only active testimonials will be shown on the site.')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('Car (Sedan, Hatchback)', 'Car (Sedan, Hatchback)'), ('SUV / MUV', 'SUV / MUV'), ('Van / Minibus', 'Van / Minibus'), ('Truck', 'Truck'), ('Trolley / Trailer', 'Trolley / Trailer'), ('Construction (e.g., JCB)', 'Construction (e.g., JCB)'), ('Other Commercial Vehicle', 'Other Commercial Vehicle')], max_length=100)),
                ('make_model', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
